/* * *******************************************************************************
* This file is part of SpiceCRM FulltextSearch. SpiceCRM FulltextSearch is an enhancement developed
* by aac services k.s.. All rights are (c) 2016 by aac services k.s.
*
* This Version of the SpiceCRM FulltextSearch is licensed software and may only be used in
* alignment with the License Agreement received with this Software.
* This Software is copyrighted and may not be further distributed without
* witten consent of aac services k.s.
*
* You can contact us at info@spicecrm.io
******************************************************************************* */

if(void 0===SpiceCRM)var SpiceCRM={};SpiceCRM.fts={displayAggregates:!1,page:0,aggregates:[],isSearching:!1,clearSearch:function(){this.aggregates=[],$("#ftssearchterm").val(""),this.submitSearch()},submitSearch:function(){this.isSearching=!0,$("table .list").html("... loading ..."),$.post("KREST/fts/search/"+$("#search_form input[name=module]").val(),JSON.stringify({searchterm:$("#ftssearchterm").val(),module:$("#search_form input[name=module]").val(),aggregates:this.aggregates,page:this.page}),function(e,t,a){$("table .list").html(e.result),$("#ftsaggregates").html(e.aggregates),$("ul.clickMenu").each(function(e,t){$(t).sugarActionMenu()}),$(".selectActionsDisabled").children().each(function(e){$(this).attr("onclick","").unbind("click")});var s=$("#selectCountTop").attr("value");void 0!==s&&"0"!=s&&sugarListView.prototype.toggleSelected(),SpiceCRM.fts.isSearching=!1})},setAggreggates:function(e){$("#ftsaggregates").html(atob(e))},handleKeyPress:function(e){if(13==e.keyCode)return this.page=0,SpiceCRM.fts.submitSearch(),!1},handleAggClick:function(e,t){if(!this.isSearching){e.currentTarget.setAttribute("src","themes/SpiceTheme/images/checkbox_indetermined.png");var a=this.aggregates.indexOf(t);-1==a?this.aggregates.push(t):this.aggregates.splice(a,1),this.page=0,this.submitSearch()}},getAggregates:function(){var a=[];return $(".aggitem").each(function(e,t){t.checked&&a.push(t.name)}),a},toggleAggregates:function(){this.displayAggregates?($("#ftsaggregates").hide(500),$("#ftsaggregatetoggleimage").attr("src","themes/SpiceTheme/images/downarrow.gif")):($("#ftsaggregates").show(500),$("#ftsaggregatetoggleimage").attr("src","themes/SpiceTheme/images/uparrow.gif")),this.displayAggregates=!this.displayAggregates},paginate:function(e){switch(e){case"first":this.page=0;break;case"prev":this.page--;break;case"next":this.page++;break;case"last":this.page="last"}this.submitSearch()}};